// Подписи действий из журнала аудита (`audit_log.action`) для ленты «Действия» в профиле
// пользователя. Неизвестный код показывается как есть — новое действие на бэкенде не ломает ленту.

export const AUDIT_ACTION_LABELS: Record<string, string> = {
  "mark.create": "Поставил(а) отметку",
  "mark.update": "Изменил(а) отметку",
  "mark.delete": "Удалил(а) отметку",
  "period.create": "Оформил(а) период отсутствия",
  "day.submit": "Сдал(а) день",
  "day.resubmit": "Пересдал(а) день",
  "task.create": "Создал(а) задачу",
  "task.update": "Изменил(а) задачу",
  "task.delete": "Удалил(а) задачу",
  "task.submit": "Отправил(а) задачу на проверку",
  "task.accept": "Принял(а) задачу",
  "task.return": "Вернул(а) задачу на доработку",
  "task.remind": "Напомнил(а) о задаче",
  "task.template_create": "Создал(а) шаблон задачи",
  "task.template_delete": "Удалил(а) шаблон задачи",
  "task.template_schedule": "Настроил(а) расписание шаблона",
  "task.scheduled_create": "Задача создана по расписанию",
  "task.scheduled_skip": "Задача по расписанию пропущена",
  "dossier.profile_update": "Изменил(а) досье",
  "dossier.guardian_add": "Добавил(а) представителя",
  "dossier.guardian_update": "Изменил(а) представителя",
  "dossier.guardian_delete": "Удалил(а) представителя",
  "dossier.note_add": "Добавил(а) запись индивидуальной работы",
  "dossier.note_delete": "Удалил(а) запись индивидуальной работы",
  "dossier.follow_up_done": "Закрыл(а) вопрос «вернуться к…»",
  "dossier.task_update": "Досье обновлено из задачи",
  "dossier.import": "Загрузил(а) досье из Excel",
  "student.create": "Добавил(а) студента",
  "student.update": "Изменил(а) данные студента",
  "student.status_change": "Сменил(а) статус студента",
  "student.delete": "Удалил(а) студента",
  "student.anonymize": "Обезличил(а) студента",
  "student.absence_sheet": "Сформировал(а) лист пропусков",
  "passport.view": "Открыл(а) соц. паспорт группы",
  "passport.summary": "Открыл(а) сводку соц. паспорта",
  "passport.export": "Выгрузил(а) соц. паспорт",
  "group.create": "Создал(а) группу",
  "group.update": "Изменил(а) группу",
  "group.delete": "Удалил(а) группу",
  "group.roster_sheet": "Сформировал(а) список группы",
  "department.create": "Создал(а) отделение",
  "department.rename": "Переименовал(а) отделение",
  "curator_assignment.end": "Снял(а) куратора с группы",
  "calendar.upsert": "Изменил(а) учебный календарь",
  "calendar.delete": "Убрал(а) день из календаря",
  "user.create": "Создал(а) пользователя",
  "user.role_change": "Сменил(а) роль пользователя",
  "user.username_change": "Сменил(а) логин пользователя",
  "user.password_set": "Выдал(а) пароль",
  "user.unlock": "Снял(а) блокировку входа",
  "user.delete": "Удалил(а) пользователя",
  "user.anonymize": "Обезличил(а) пользователя",
  "password.change": "Сменил(а) свой пароль",
};

/** Области для фильтра ленты: значение уходит на сервер как `area` (начало кода действия). */
export const AUDIT_AREAS: [string, string][] = [
  ["", "Все действия"],
  ["mark", "Отметки"],
  ["day", "Сдача дней"],
  ["task", "Задачи"],
  ["dossier", "Досье"],
  ["student", "Студенты"],
  ["passport", "Соц. паспорт"],
  ["group", "Группы"],
  ["user", "Пользователи"],
];

export function auditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] ?? action;
}
